= What to expect from 1.4!

:hp-tags: TGB's Extension,Update

[%hardbreaks]
*Hey!* I've been working on some cool new features to TGB's Extension 1.4, they include:

"Query Parameter (parameter)"::

It acts just like the *$_GET* method in *PHP*.
Each parameter is set in the url by using the following format: +
`*?<param>=<value>&<paramN>=<value>*`
+
Example: +
*URL*: http://scratch.mit.edu/projects/41561058/?holidayspecial=false +
Block output when using *holidayspecial* as a parameter: *false*

"Custom Hash (hash number)"::

It returns any hashes in the URL that aren't one of these -> *[#editor, #player, #fullscreen]* +
TIP: This block doesn't really work well because Scratch removes *any* extra hashes from the URL after switching viewing modes. + 
+
This block *might* be removed from the final release.

"Is tab visible?"::

It reports *true* if the tab is visible to the user. This block can be useful to prevent glitches when a tab is not active. +
 +
In many Scratch games today, you can observe *strange behavior* when you leave them running on a different tab, specially when it involves *cloning* stuff. Their scripts kind of *stop running* when the tab isn't active and run everything in bulk when the tab becomes active again.

The "Browser Language" block::
It is an alternative to the *"User Language"* block that *returns the language used in the browser*, not Scratch. As some people use Scratch in languages other than their native one *(me included)*, I thought this could be useful in determining the *real* user's language!

*Sensing* blocks will be more secure.::
They will only work when the Flash player is focused. This new behavior will fix a security hole that allowed people to *steal passwords* by recording key presses from *outside* the player.

The "atan2" block will work as expected.::
This block originally had it's input values *inverted (x was being used in place of y and vice-versa)* but now it works as intended!

Update Warnings!::
It must be really frustrating to have to check the forum post *every* time to find out if there is an update, so I decided to include an *update warning* to tell you when there is a *new* version of *TGB's Extension*!